### ISSUE TITLE
Fix WrongParseException.java:  serial version ID

### ISSUE THREAD

**Issue by MariusLovesPizza** [plansoft-it/GestioneOrari#34]
Modifica WrongParseException.java, aggiungere il serialVersioneUID, richiesto dal compilatore

**Comment by Wabri** [comment]
Puoi indicare nell'issue la classe a cui ti riferisci?

**Comment by MariusLovesPizza** [comment]
> 
> 
> Puoi indicare nell'issue la classe a cui ti riferisci?

Cosi, o tra parentesi? guardando la cronologia degli altri issue mi sembra che sono in questa forma, senza parentesi.

**Comment by Wabri** [comment]
Così ok
