### ISSUE TITLE
Rendere eseguibile il pacchetto

### ISSUE THREAD

**Issue by Wabri** [plansoft-it/GestioneOrari#41]
Per poter generare un jar, che è un archivio java eseguibile. Per poterlo creare è necessario definire un manifest, qui la guida: https://docs.oracle.com/javase/tutorial/deployment/jar/manifestindex.html

**Comment by antoniocaia** [comment]
@Wabri devo aggiungere anche il file con i comandi per compilare e creare il jar?

**Comment by Wabri** [comment]
Se vuoi basta anche modificare il readme, metti un paragrafo di compilazione e ce lo scrivi sotto passo passo.
